version: '2'
services:
  postgres:
    image: 'postgres'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    env_file:
      - config/.dev.env
    ports:
      - '5432:5432'