version: '2.2'
services:
  api-service:
    build: .
    ports:
      - 9245:5000
    volumes:
      - ./:/usr/src/app/
    environment:
      FLASK_ENV: "dev"
    network_mode: "host"
    depends_on:
      - postgres
  postgres:
    image: 'postgres:13.4-buster' 
    restart: always 
    ports:
      - 9256:5432
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    env_file:
      - config/.dev.env

