version: '2.2'
services:
  api-service:
    build: .
    ports:
      - 9245:5000
    volumes:
      - ./:/usr/src/app/
    environment:
      FLASK_ENV: "dev"
    depends_on:
      - postgres
  postgres:
    image: 'postgres'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    env_file:
      - config/.dev.env
  mail_catcher:
    image: dockage/mailcatcher:0.6.5
    ports:
      - 1069:1080
      - 1029:1025