version: '2.2'
services:
  api-service:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/src/app/
    environment:
      FLASK_ENV: "dev"
    depends_on:
      - postgres
  postgres:
    image: 'postgres'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    env_file:
      - config/.dev.env
    ports:
      - '5432:5432'