"""empty message

Revision ID: 1b85d62b9d3f
Revises: e1967f120b4a
Create Date: 2021-08-21 05:32:37.135770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b85d62b9d3f'
down_revision = 'e1967f120b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatment', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment', sa.Column('status', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
