"""empty message

Revision ID: 4104545fddcc
Revises: 85566eadc706
Create Date: 2021-08-20 03:12:59.412288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4104545fddcc'
down_revision = '85566eadc706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('session_adjustment', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('session_stop', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'session_stop')
    op.drop_column('role', 'session_adjustment')
    # ### end Alembic commands ###
