"""empty message

Revision ID: 45ad5d4c0993
Revises: 830dc1a45ef5
Create Date: 2021-08-20 03:17:18.209700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ad5d4c0993'
down_revision = '830dc1a45ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('role_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'role_code')
    # ### end Alembic commands ###
