"""empty message

Revision ID: 4df4a20cdf06
Revises: 4104545fddcc
Create Date: 2021-08-20 03:15:16.057105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4df4a20cdf06'
down_revision = '4104545fddcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'role_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('role_code', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
