"""empty message

Revision ID: 5d5032784ed4
Revises: b300f14ea05f
Create Date: 2021-08-21 05:33:47.131270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5032784ed4'
down_revision = 'b300f14ea05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment', sa.Column('state', sa.String(length=12), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatment', 'state')
    # ### end Alembic commands ###
