"""empty message

Revision ID: 60aeeee4c0b3
Revises: 10befe2c2bfa
Create Date: 2021-08-21 01:20:19.978304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60aeeee4c0b3'
down_revision = '10befe2c2bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('id_device', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'station', 'device', ['id_device'], ['id_device'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'station', type_='foreignkey')
    op.drop_column('station', 'id_device')
    # ### end Alembic commands ###
