"""empty message

Revision ID: 6900801969cd
Revises: 4df4a20cdf06
Create Date: 2021-08-20 03:16:01.550184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6900801969cd'
down_revision = '4df4a20cdf06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('role_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'role_code')
    # ### end Alembic commands ###
