"""empty message

Revision ID: 703595187c52
Revises: 8aa04fe780c1
Create Date: 2021-08-22 04:54:51.845295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '703595187c52'
down_revision = '8aa04fe780c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable',
    sa.Column('id_timetable', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id_group', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('monday', sa.JSON(), nullable=True),
    sa.Column('tuesday', sa.JSON(), nullable=True),
    sa.Column('wednesday', sa.JSON(), nullable=True),
    sa.Column('thursday', sa.JSON(), nullable=True),
    sa.Column('friday', sa.JSON(), nullable=True),
    sa.Column('saturday', sa.JSON(), nullable=True),
    sa.Column('sunday', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id_group'], ['group.id_group'], ),
    sa.PrimaryKeyConstraint('id_timetable'),
    sa.UniqueConstraint('name')
    )
    op.add_column('group', sa.Column('default_timetable', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'group', 'timetable', ['default_timetable'], ['id_timetable'])
    op.add_column('location', sa.Column('timetable', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'location', 'timetable', ['timetable'], ['id_timetable'])
    op.add_column('role', sa.Column('manage_timetables', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('manage_dates', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('id_location', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('user', sa.Column('timetable', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'user', 'timetable', ['timetable'], ['id_timetable'])
    op.create_foreign_key(None, 'user', 'location', ['id_location'], ['id_location'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'timetable')
    op.drop_column('user', 'id_location')
    op.drop_column('role', 'manage_dates')
    op.drop_column('role', 'manage_timetables')
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_column('location', 'timetable')
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'default_timetable')
    op.drop_table('timetable')
    # ### end Alembic commands ###
