"""empty message

Revision ID: 830dc1a45ef5
Revises: 6900801969cd
Create Date: 2021-08-20 03:17:05.794843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830dc1a45ef5'
down_revision = '6900801969cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'role_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('role_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
