"""empty message

Revision ID: 85566eadc706
Revises: 466911378ff7
Create Date: 2021-08-20 03:03:12.466628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85566eadc706'
down_revision = '466911378ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'manager_login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('manager_login', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
