"""empty message

Revision ID: 8aa04fe780c1
Revises: a5e5681429e7
Create Date: 2021-08-21 18:30:16.488574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa04fe780c1'
down_revision = 'a5e5681429e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('manage_roles', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'manage_roles')
    # ### end Alembic commands ###
