"""empty message

Revision ID: 8d17bbe489e1
Revises: f52aab7a757e
Create Date: 2021-08-21 02:35:39.643395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d17bbe489e1'
down_revision = 'f52aab7a757e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('medic', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_constraint('session_medic_name_key', 'session', type_='unique')
    op.create_foreign_key(None, 'session', 'user', ['medic'], ['id_user'])
    op.drop_column('session', 'medic_name')
    op.add_column('treatment', sa.Column('medic', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'treatment', 'user', ['medic'], ['id_user'])
    op.drop_column('treatment', 'medic_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment', sa.Column('medic_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'treatment', type_='foreignkey')
    op.drop_column('treatment', 'medic')
    op.add_column('session', sa.Column('medic_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.create_unique_constraint('session_medic_name_key', 'session', ['medic_name'])
    op.drop_column('session', 'medic')
    # ### end Alembic commands ###
