"""empty message

Revision ID: a436e4cc1ace
Revises: 45ad5d4c0993
Create Date: 2021-08-20 03:31:07.820999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a436e4cc1ace'
down_revision = '45ad5d4c0993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
