"""empty message

Revision ID: a5e5681429e7
Revises: a7ce081aa6cd
Create Date: 2021-08-21 06:21:14.447477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e5681429e7'
down_revision = 'a7ce081aa6cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('manage_devices', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'manage_devices')
    # ### end Alembic commands ###
