"""empty message

Revision ID: a7ce081aa6cd
Revises: 97c24be7939a
Create Date: 2021-08-21 06:08:30.214761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7ce081aa6cd'
down_revision = '97c24be7939a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('ts_creation_date', sa.REAL(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'ts_creation_date')
    # ### end Alembic commands ###
