"""empty message

Revision ID: b300f14ea05f
Revises: 1b85d62b9d3f
Create Date: 2021-08-21 05:33:38.032306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b300f14ea05f'
down_revision = '1b85d62b9d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatment', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment', sa.Column('state', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
