"""empty message

Revision ID: e1967f120b4a
Revises: 8d17bbe489e1
Create Date: 2021-08-21 02:51:02.940476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1967f120b4a'
down_revision = '8d17bbe489e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('country', sa.String(length=50), nullable=True))
    op.add_column('patient', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('patient', sa.Column('race', sa.String(length=20), nullable=True))
    op.add_column('patient', sa.Column('complexity', sa.String(length=100), nullable=True))
    op.add_column('patient', sa.Column('width', sa.REAL(), nullable=True))
    op.add_column('patient', sa.Column('height', sa.REAL(), nullable=True))
    op.add_column('patient', sa.Column('allergies', sa.String(length=500), nullable=True))
    op.add_column('patient', sa.Column('medication', sa.String(length=500), nullable=True))
    op.alter_column('session', 'points',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.add_column('treatment', sa.Column('last_session_date', sa.DateTime(), nullable=True))
    op.alter_column('treatment', 'points',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.add_column('user', sa.Column('country', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'country')
    op.alter_column('treatment', 'points',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('treatment', 'last_session_date')
    op.alter_column('session', 'points',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('patient', 'medication')
    op.drop_column('patient', 'allergies')
    op.drop_column('patient', 'height')
    op.drop_column('patient', 'width')
    op.drop_column('patient', 'complexity')
    op.drop_column('patient', 'race')
    op.drop_column('patient', 'gender')
    op.drop_column('patient', 'country')
    # ### end Alembic commands ###
