"""empty message

Revision ID: f52aab7a757e
Revises: ff683a5695d9
Create Date: 2021-08-21 02:22:08.289174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f52aab7a757e'
down_revision = 'ff683a5695d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('points', sa.JSON(), nullable=False))
    op.add_column('treatment', sa.Column('points', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatment', 'points')
    op.drop_column('session', 'points')
    # ### end Alembic commands ###
