"""empty message

Revision ID: fce9e089e23b
Revises: 60aeeee4c0b3
Create Date: 2021-08-21 01:20:54.056833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fce9e089e23b'
down_revision = '60aeeee4c0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('station_id_device_fkey', 'station', type_='foreignkey')
    op.drop_column('station', 'id_device')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('id_device', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('station_id_device_fkey', 'station', 'device', ['id_device'], ['id_device'])
    # ### end Alembic commands ###
