"""empty message

Revision ID: ff683a5695d9
Revises: fce9e089e23b
Create Date: 2021-08-21 02:21:59.850342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff683a5695d9'
down_revision = 'fce9e089e23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'points')
    op.drop_column('treatment', 'points')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment', sa.Column('points', sa.VARCHAR(length=10000), autoincrement=False, nullable=False))
    op.add_column('session', sa.Column('points', sa.VARCHAR(length=10000), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
